---

- name: Install npm
  apt:
      name: 
          - openssh-client
      state: present
- name: Creates backend app directory
  file:
    path: ~/backend-app
    state: directory
- name: Copy backend files
  copy:
    src: backend
    dest: ~/backend-app

- name: "Installing Node Dependencies"
  shell: |
    cd ~/backend-app
    curl -sL https://deb.nodesource.com/setup_14.x | sudo -E bash -
    sudo apt-get install -y nodejs
    npm install
    npm run build
    nmp i
    npm i -g pm2
    cd ~/backend-app/dist
    pm2 stop default
    pm2 start npm -- start
    pm2 start main.js
  register: execute_node

- name: print message
  debug:
    msg: "{{ execute_node.stdout_lines }}"

- name: Configure pm2 to start as service
  become: true
  shell: |
    env PATH=$PATH:/usr/local/bin pm2 startup systemd -u ubuntu --hp /home/ubuntu
